openapi: 3.0.0
info:
  title: Sanctions List API
  version: '1.0'
  description: 'cubemos Sanctions list API is a RESTful API which can be used to avoid prosecution and be compliant with international regulation on sanctions, AML and financial crime '
  contact:
    name: cubemos gmbh
    url: www.cubemos.com
    email: meet@cubemos.com
  license:
    name: cubemos license
  termsOfService: 'https://www.cubemos.com/general-terms/'
servers:
  - url: api.cubemos.com
    description: ''
paths:
  /search/entities/person:
    post:
      summary: Search for a person through sanction lists
      operationId: post-search-entities-organizations
      responses:
        '200':
          description: 'The request was created successfully and the results are available as an array. If the array is empty, there were no matching persons found in the desired sanction lists.'
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/personSearchResult'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      description: Search a person through sanction lists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/personSearch'
            examples:
              Example:
                value:
                  person_search:
                    full_name: john junior senior smith
                    first_names: john
                    middle_names: junior senior
                    last_names: smith
                    aliases:
                      - don john
                      - godfather
                    gender: male
                    dob: 01.01.1950
                    nationalities: DE
                    sanction_lists:
                      - UN-Sanctions List
                      - EU-Financial Sanctions List
                  advanced_attributes:
                    title: Prime minister of a country
                    full_address: 'Herman Straße 2, 12345 Berlin, Germany'
                    dob_year_ambiguity: '1950, 1952'
                    must_attributes: 'full_name, dob'
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
          text/html:
            schema:
              type: object
              properties: {}
          text/plain:
            schema:
              type: object
              properties: {}
          application/EDI-X12:
            schema:
              type: object
              properties: {}
        description: Payload request schema for single search
      parameters: []
    parameters: []
  /search/entities/organization:
    post:
      summary: Search for an organization through sanction lists
      operationId: post-search-entities-organizations
      responses:
        '200':
          description: 'The request was created successfully and the results are available as an array. If the array is empty, there were no matching organization found in the desired sanction lists.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organizationSearchResult'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/organizationSearch'
        description: Payload request schema for single search
      description: "POST call for the single search on an organization's details through the desired sanction lists"
    parameters: []
  /search/location/address:
    post:
      summary: Search for an entity based on an address through sanction lists
      operationId: post-search-address-geo
      responses:
        '200':
          description: 'The request was created successfully and the results are available as an array. If the array is empty, there were no matching persons found in the desired sanction lists.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locationSearchResult'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addressSearch'
            examples:
              Example:
                value:
                  sanction_lists:
                    - EU-financial sanctions list
                    - UN-sanctions list
                  address:
                    country: DE
                    zip_code: 12345
                    city: Berlin
                    street: Hermann Straße 1
        description: Payload request scheme for single search
      description: Search on an entity through the desired sanction lists in at an address
    parameters: []
  /bulksearch/entities/person:
    post:
      summary: Search for multiple persons through sanction lists
      operationId: post-bulksearch-entities-person
      responses:
        '200':
          description: 'The request was created successfully and the results are available as an array. If the array is empty, there were no matching persons found in the desired sanction lists.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/personBulkSearchResult'
      description: Searches on multiple persons through the sanction lists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/personBulkSearch'
            examples: {}
          application/xml:
            schema:
              $ref: '#/components/schemas/personBulkSearch'
          multipart/form-data:
            schema:
              type: object
              properties: {}
        description: Input payload for the bulk search query on persons
      parameters: []
  /search/location/geo:
    post:
      summary: Search for an entity based on geographical co-ordinates through sanction list
      operationId: post-search-location-geo
      responses:
        '200':
          description: 'The request was created successfully and the results are available as an array. If the array is empty, there were no matching entities were found in the desired sanction lists.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locationSearchResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/geoSearch'
            examples:
              Example:
                value:
                  sanction_lists:
                    - EU-financial sanctions list
                    - UN-sanctions list
                  geo:
                    latitude: 0.1234
                    logitude: 0.1234
                    radius: 500
        description: Payload request scheme for single search
      description: Search on an entity through the desired sanction lists in a radius around a geographical co-ordinate
      parameters: []
components:
  schemas:
    personBasicSearch:
      title: personBasicSearch
      type: object
      description: Basic search identifiers for a person through a sanction list
      x-examples: {}
      properties:
        full_name:
          type: string
          description: Full name of a person (first_names + middle_names + last_names )
          example: john junior senior smith
        first_names:
          type: string
          description: All the first names of the person
          example: john
        middle_names:
          type: string
          description: All the middle names of the person
          example: junior senior
        last_names:
          type: string
          description: All the last names of the person
          example: smith
        aliases:
          type: array
          description: 'All the aliases of the person as an array '
          example: 'don john, godfather'
          uniqueItems: true
          items:
            type: string
        gender:
          type: string
          description: 'Gender of the person '
          example: male
        dob:
          type: string
          description: Date of birth of the person
          example: 01.01.1950
        nationalities:
          type: array
          description: Nationalities of the person as an array of 2 letter ISO country code
          example: USA
          items:
            type: string
        sanction_lists:
          type: array
          description: All the sanction lists as an array through which the search has to be made
          example: 'UN Sanctions List, EU Financial Sanctions List'
          uniqueItems: true
          items:
            type: string
      required:
        - full_name
        - sanction_lists
    personAdvancedsearch:
      title: personAdvanced
      type: object
      description: Advanced search for a person through a sanction list
      properties:
        title:
          type: string
          description: Job title or positional title held by the person
          example: Prime minister of a country
        full_address:
          type: string
          example: '12, street, 12345 city, country'
          description: Full address as a string from door number to country
        dob_year_ambiguity:
          type: array
          description: Possible birth years if the date of birth is not clear
          example: '1950, 1952'
          items:
            type: integer
        must_attributes:
          type: array
          description: |-
            Identifiers of the entry fields against which the match similarity has to be 100% in the results
            The identifiers can be from the basic fields and advanced fields
          example: 'full_name, dob'
          items:
            type: string
    personSearch:
      title: personSearch
      type: object
      description: The identifiers based on which the search will be performed for a person through the desired sanction lists
      x-examples: {}
      properties:
        person_search:
          $ref: '#/components/schemas/personBasicSearch'
        advanced_attributes:
          $ref: '#/components/schemas/personAdvancedsearch'
    personSearchResult:
      title: personSearchResult
      description: Response payload for the query on a person through the desired sanction lists
      type: object
      properties:
        persons_identified:
          type: integer
          description: Number of persons identified matching to the input query
        persons:
          type: array
          items:
            $ref: '#/components/schemas/person'
    sanctionListEntryPerUid:
      title: sanctionListEntryPerUid
      type: object
      description: ''
      properties:
        number_of_entries:
          type: integer
          description: number of entries with the same unique id in the sanction list
        array_of_list_entries:
          type: array
          description: raw entries from the sanction list
          items:
            type: string
        sanction_list:
          type: string
          description: The sanction list in which a valid result was found
    organizationBasicSearch:
      title: orgafuzzysearch
      type: object
      properties:
        organization_name:
          type: string
          example: cubemos gmbh
          description: Name of the organization for which the search through sanction lists has to be made
        address:
          type: string
          example: 'mehlbeerenstraße 2, 82024 taufkirchen'
          description: Full address of the organization
        head_quarter_country:
          type: string
          example: germany
          description: Country name in which the head quarter is located
        sanction_list:
          type: array
          description: Sanction lists through which the search has to be made
          items:
            type: string
        match_similarity_threshold:
          type: string
          example: '0.5'
          description: Threshold value for the matching similarity below which the results will not be returned
      required:
        - organization_name
        - sanction_list
      description: Basic search identifiers for an organization through a sanction list
    organizationAdvancedsearch:
      title: orgafilterssearch
      type: object
      properties:
        strict_entry_identifiers:
          type: string
          description: |-
            Identifiers of the entry fields against which the match similarity has to be 100% in the results
            The identifiers can be from the basic fields and advanced fields
      description: Advanced search for an organization through a sanction list
    organizationSearch:
      title: searchOrganization
      type: object
      description: The identifiers based on which the search will be performed for a organization through the desired sanction lists
      properties:
        basic:
          $ref: '#/components/schemas/organizationBasicSearch'
        advanced:
          $ref: '#/components/schemas/organizationAdvancedsearch'
    organization:
      title: organization
      type: object
      properties:
        name:
          type: string
          description: Sanction lists in which the results were found
        address:
          $ref: '#/components/schemas/address'
        headquarter_country:
          description: |
            Match similarity for each search result corresponding to the sanction list
          type: string
        aliases:
          type: array
          description: "List of aliases that the organization has for it's name. "
          items:
            type: string
      description: organization details
    geo:
      title: geo
      type: object
      description: Basic search identifiers for an entity through a sanction list based on geographical co-ordinates
      properties:
        latitude:
          type: number
          description: The latitude of the location
        logitude:
          type: number
          description: The longitude of the location
        radius:
          type: integer
          description: Search radius around the input latitude and logitude in meters
      required:
        - latitude
        - logitude
        - radius
    organizationSearchResult:
      title: organizationSearchResult
      type: object
      description: Response payload for the query on a organization through the desired sanction lists
      properties:
        organizations_identified:
          description: Number of organizations found
          type: integer
        organizations:
          $ref: '#/components/schemas/organization'
    locationSearchResult:
      title: geoSearchResult
      type: object
      description: Response of a search query based on geographical co-ordinates through the desired sanction lists
      properties:
        number_of_matches:
          description: Indicates what type of an entity is searched for
          type: integer
        persons:
          $ref: '#/components/schemas/personSearchResult'
        organizations:
          $ref: '#/components/schemas/organizationSearchResult'
      required:
        - number_of_matches
    personBulkSearch:
      title: personBulkSearch
      type: object
      description: Bulk search payload for persons
      properties:
        number_of_persons:
          type: integer
          description: Number of persons to search for through the desired sanction lists
        persons:
          type: array
          items:
            $ref: '#/components/schemas/personSearch'
    personBulkSearchResult:
      title: personBulkSearchResult
      type: object
      description: Response payload of the bulk search on persons
      properties:
        number_of_persons:
          type: integer
          description: Number of persons whose results have returned. Same as the input parameter of number of persons. The entry for which no results were found are denoted with null in the persons_results array.
        persons_results:
          type: array
          items:
            $ref: '#/components/schemas/personSearchResult'
    addressSearch:
      title: addressSearch
      type: object
      description: query payload for an address search
      properties:
        sanction_lists:
          type: array
          description: First line of the address
          items:
            type: string
        address:
          $ref: '#/components/schemas/address'
      x-examples: {}
    person:
      title: person_
      type: object
      properties:
        first_name:
          type: string
          description: First name of the query
        middle_name:
          type: string
        last_name:
          type: string
        dob:
          type: string
          description: Date of birth of the person
        gender:
          type: string
          description: Gender of the person
        aliases:
          type: array
          description: List of all the aliases that the person has
          items:
            type: string
        nationalities:
          type: array
          description: Nationalities of a person denoted as by their respective ISO country codes
          items:
            type: string
        array_of_sanction_lists:
          type: array
          items:
            $ref: '#/components/schemas/sanctionListEntryPerUid'
    address:
      title: address
      type: object
      properties:
        country:
          type: string
        zip_code:
          type: integer
        city:
          type: string
        street:
          type: string
      description: Basic search identifiers for an entity through a sanction list based on an address
    geoSearch:
      title: geoSearch
      type: object
      description: ''
      properties:
        sanction_lists:
          type: array
          items:
            type: string
        geo:
          $ref: '#/components/schemas/geo'
  securitySchemes:
    cubemos_api_key:
      name: API Key
      type: apiKey
      in: query
